### ISSUE TITLE
Все ок. Пожелание.

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#100]
Доброго дня, Наталья?
Только хотел написать что 5.5.40 в БД не сохраняет, уже исправили. Отлично.
Вопрос-пожелание: сделать "бессрочное" хранение данных/значений в БД (сейчас макс. 500 дней), на ответственность обслуживающего.
Типа "бессрочно" или значок бесконечности или иное обозначение.

И мини-вопросик : "Сохранять для TimeLine" это что за опция?

Supmik@ya.ru
Михаил.

![snapshot](http://docs.ih-systems.com:40000/report/XuMirXG9l.png)

- browser
  - name: Electron
  - version: 13.1.2
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: amd64
  - osUptime: 0d 1h 17m
  - uptime: 0d 0h 46m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.5.42
  - project: intrascada_energy
  - projectVersion: 5.5
- memory
  - os_total_free: 15.4 Gb / 13.8 Gb
  - process_rss: 96.5 Mb
  - process_heap_total: 28.4 Mb
  - process_heap_used: 20.3 Mb

**Comment by goodspeed1986** [comment]
Бессрочно добавим. Про Сохранять для TimeLine информация будет в документации
