### ISSUE TITLE
Съезжает контейнер

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#102]
Контейнер словно ушел наверх.
Со всеми элементами.
(При этом, например, некий выделенный объект имеет норм. Y=140, т.е. на примерно нужном месте относительно контейнера).

Имею только возможность изменения  ширины контейнера, высоты, но не положения.

/Яндекс-браузер.

Но и в вашей десктоп.версии аналогичная ситуация. Этот контейнер тоже ушедший наверх.

Как вернуть редактируемый контейнер на место, спустить вниз?

![snapshot](http://docs.ih-systems.com:40000/report/6TP_e5Tg-.png)

- browser
  - name: Yandex Browser
  - version: 21.6.1.274
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: amd64
  - osUptime: 0d 3h 17m
  - uptime: 0d 0h 29m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.5.42
  - project: intrascada_energy
  - projectVersion: 5.5
- memory
  - os_total_free: 15.4 Gb / 14.7 Gb
  - process_rss: 77 Mb
  - process_heap_total: 26.6 Mb
  - process_heap_used: 18.8 Mb

**Comment by goodspeed1986** [comment]
Для зума полотна необходимо использовать alt+mouse scroll, для перемещения зажмите пробел, появится рука и можно тащить полотно по экрану.
