### ISSUE TITLE
Экспорт/импорт папки с контейнерами

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#109]
Проблема с экпортом/импортом папки с контейрами из демо проекта.

![snapshot](http://docs.ih-systems.com:40000/report/9UWIPYpui.png)

- browser
  - name: Chrome
  - version: 92.0.4515.107
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm64
  - osUptime: 0d 1h 9m
  - uptime: 0d 0h 55m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.5.46
  - project: demo_1627904047469
  - projectVersion: 5.5
- memory
  - os_total_free: 963.7 Mb / 165.2 Mb
  - process_rss: 82.9 Mb
  - process_heap_total: 24.5 Mb
  - process_heap_used: 18.4 Mb

**Comment by nimargolis** [comment]
Проблема с выгрузкой папки с контейнерами
