### ISSUE TITLE
DemoProject

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#116]
В демо-проекте, идущем с IS по умолчанию, не работают(не привязаны к контейнеру) кнопки переходов 1-2-3-4 меню страницы.

![snapshot](http://docs.ih-systems.com:40000/report/kEOPHaS0g.png)

- browser
  - name: Yandex Browser
  - version: 21.6.3.757
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: amd64
  - osUptime: 0d 0h 42m
  - uptime: 0d 0h 41m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.5.46
  - project: demo_1628063478636
  - projectVersion: 5.5
- memory
  - os_total_free: 5.6 Gb / 3.7 Gb
  - process_rss: 70.8 Mb
  - process_heap_total: 22.1 Mb
  - process_heap_used: 17.7 Mb

**Comment by goodspeed1986** [comment]
Изменился способ смены контейнеров и контекста в контейнерах. Если необходимо восстановить функционал, то нужно перепривязать одиночный клик на те контейнеры, которые необходимо отобразить. В демо проекте у себя поправим.
