### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#119]
Опечатка.
Написано "Спарва", вместо "Справа".

![snapshot](http://docs.ih-systems.com:40000/report/OFtu6o39g.png)

- browser
  - name: Chrome
  - version: 92.0.4515.131
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm64
  - osUptime: 8d 18h 46m
  - uptime: 1d 17h 52m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.5.50
  - project: demo_1627904047469
  - projectVersion: 5.5
- memory
  - os_total_free: 963.7 Mb / 228.1 Mb
  - process_rss: 89.5 Mb
  - process_heap_total: 26.2 Mb
  - process_heap_used: 23.2 Mb

**Comment by nimargolis** [comment]
Исправлено в v5.5.59
