### ISSUE TITLE
не помещаются headers и их не видно

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#123]
в поле headers если длинная строка, то не все все видно, нужно стрелками вправо/влево кликать, чтобы посмотреть все заголовки. Многострочное поле решило бы эту проблему.
Спасибо

![snapshot](http://docs.ih-systems.com:40000/report/DnnpYpfs-.png)

- browser
  - name: Chrome
  - version: 92.0.4515.131
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm
  - osUptime: 0d 0h 12m
  - uptime: 0d 0h 12m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.5.55-beta
  - project: demo_1628579709098
  - projectVersion: 5.5
- memory
  - os_total_free: 7.6 Gb / 7.3 Gb
  - process_rss: 73.9 Mb
  - process_heap_total: 14.1 Mb
  - process_heap_used: 12.7 Mb

**Comment by nimargolis** [comment]
Выпущена версия плагина 5.5.2
