### ISSUE TITLE
Орфографическая ошибка

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#127]
вместо СПАРВА нужно СПРАВА

![snapshot](http://docs.ih-systems.com:40000/report/0pLQP0QUL.png)

- browser
  - name: Chrome
  - version: 92.0.4515.131
- os
  - name: Windows
  - version: NT 6.1
  - versionName: 7
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm
  - osUptime: 0d 2h 29m
  - uptime: 0d 2h 25m
  - port: 8088
  - server: intrahouse_v5
  - serverVersion: 5.5.50
  - project: demo_1628754325537
  - projectVersion: 5.5
- memory
  - os_total_free: 924.8 Mb / 656 Mb
  - process_rss: 70.9 Mb
  - process_heap_total: 20 Mb
  - process_heap_used: 15.9 Mb

**Comment by nimargolis** [comment]
Исправлено в v5.5.59
