### ISSUE TITLE
Названия переменных Modbus

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#128]
Сейчас требуется называть все переменные Modbus уникальными именами. Все логично, если все переменные находятся в одной папке.

Если я разделяю переменные по папкам, то просится возможность сохранить одинаковые названия внутри разных папок.

Мой пример.
Две одинаковые приточные установки.
Я создаю папку, называю ее К1. Создаю переменные внутри этой папки, например "Работа насоса".
Для второй приточной установки мне будет намного удобнее и быстрее скопировать папку К1, назвать ее К1а и оставить внутри папки переменные без изменения имени. Именно так реализовано в EcoStruxure. И это очень удобно.

Спасибо.

![snapshot](http://docs.ih-systems.com:40000/report/ap_1wRgOr.png)

- browser
  - name: Chrome
  - version: 92.0.4515.131
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm64
  - osUptime: 10d 4h 12m
  - uptime: 0d 0h 56m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.5.50
  - project: demo_1627904047469
  - projectVersion: 5.5
- memory
  - os_total_free: 963.7 Mb / 235.9 Mb
  - process_rss: 81.4 Mb
  - process_heap_total: 26.7 Mb
  - process_heap_used: 21.6 Mb

**Comment by nimargolis** [comment]
Решено v5.5.140 Настройка в манифесте плагина "innerId":1
Версия плагина modus 5.5.5
