### ISSUE TITLE
Плагины

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#132]
После обновления пропала возможность установить новый плагин.

![snapshot](http://docs.ih-systems.com:40000/report/AO1WJistm.png)

- browser
  - name: Opera
  - version: 78.0.4093.184
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm
  - osUptime: 1d 2h 38m
  - uptime: 0d 0h 0m
  - port: 8088
  - server: intrahouse_v5
  - serverVersion: 5.5.80
  - project: BlinovaNew_12
  - projectVersion: 5.5
- memory
  - os_total_free: 924.2 Mb / 315.7 Mb
  - process_rss: 54.9 Mb
  - process_heap_total: 11.2 Mb
  - process_heap_used: 10.3 Mb

**Comment by nimargolis** [comment]
Кнопка Установить восстановлена v5.5.82. Начиная с 5.5.80 сылку для скачивания система получает от сервера обновлений. Добавлен вариант для плагинов, требующих лицензии
