### ISSUE TITLE
Журнал аварий. Фон

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#133]
Не изменяется фон журнала аварий.
Всегда белый

![snapshot](http://docs.ih-systems.com:40000/report/4nx0pLhKY.png)

- browser
  - name: Chrome
  - version: 92.0.4515.159
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm64
  - osUptime: 3d 21h 44m
  - uptime: 2d 2h 42m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.5.83
  - project: demo_1627904047469
  - projectVersion: 5.5
- memory
  - os_total_free: 963.7 Mb / 286.5 Mb
  - process_rss: 98.7 Mb
  - process_heap_total: 27.5 Mb
  - process_heap_used: 23.9 Mb

**Comment by nimargolis** [comment]
Полная кастомизация цветов журналов начиная с версии 5.9.9
