### ISSUE TITLE
Журнал событий.

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#134]
Не фиксируется время пропадания аварии.
Очень нужна данная запись в журнале.

![snapshot](http://docs.ih-systems.com:40000/report/z5YHAHIi-.png)

- browser
  - name: Electron
  - version: 13.1.2
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm64
  - osUptime: 4d 1h 22m
  - uptime: 0d 0h 21m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.5.83
  - project: demo_1627904047469
  - projectVersion: 5.5
- memory
  - os_total_free: 963.7 Mb / 416.7 Mb
  - process_rss: 79.3 Mb
  - process_heap_total: 25.5 Mb
  - process_heap_used: 22.5 Mb

**Comment by nimargolis** [comment]
Запись делается, если в тревогах ввести сообщение в пункте Норма
