### ISSUE TITLE
Флаг запись в канале переключается некорректно

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#135]
Создаю переменную Modbus.
Разрешаю только чтение.
Проверяю - все работает.
Только после этого разрешаю запись.
Для изменения значения переменной использую команды.
Запись переменной не происходит.
Если значение переменной принудительно записать из плагина через канал - запись осуществляется.
Ничего не переделываю, не меняю, перезагружаю IntraScada.
Все начинает работать.

![snapshot](http://docs.ih-systems.com:40000/report/F6uqwgDWk.png)

- browser
  - name: Electron
  - version: 13.1.2
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm64
  - osUptime: 6d 18h 34m
  - uptime: 0d 0h 1m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.5.86
  - project: demo_1627904047469
  - projectVersion: 5.5
- memory
  - os_total_free: 963.7 Mb / 373.1 Mb
  - process_rss: 73.9 Mb
  - process_heap_total: 22.2 Mb
  - process_heap_used: 16.6 Mb

**Comment by nimargolis** [comment]
Решено v5.5.143
