### ISSUE TITLE
Вызов диалогового окна со стороны сервера

### ISSUE THREAD

**Issue by goodspeed1986** [intrahouseio/ih-v5#160]
Реализовать механизм вызова диалогового окна со стороны сервера для конкретного пользователя. Применение в домофонии, при оповещении о критической ситуации.

**Comment by nimargolis** [comment]
Можно вызвать showDialog из сценария для пользователя (группы). 
Также добавлен showDialog из скрипта визуализации для текущего пользователя(экрана)
