### ISSUE TITLE
Возможно ошибка

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#162]
Кнопка "Выкл" в данный момент как бы не активна (устройство отключено). Но при клике по ней прописываются команды "Выключить" и реально в отладчике Megad идут команды на контроллер. То же самое и с кнопкой "Вкл" при включенном состоянии устройства. По идее если кнопка не активна то и команды не должны формироваться

![snapshot](http://docs.ih-systems.com:40000/report/D2zbBgJXb.png)

- browser
  - name: Opera
  - version: 80.0.4170.63
- os
  - name: Windows
  - version: NT 6.1
  - versionName: 7
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm
  - osUptime: 1d 22h 47m
  - uptime: 0d 0h 2m
  - port: 8089
  - server: intrahouse_v5
  - serverVersion: 5.5.114
  - project: project_berezovaya15
  - projectVersion: 5.5
- memory
  - os_total_free: 3.7 Gb / 2.6 Gb
  - process_rss: 68.5 Mb
  - process_heap_total: 12.9 Mb
  - process_heap_used: 11.8 Mb

**Comment by goodspeed1986** [comment]
В данном случае реализовано чисто визуальное представление состояние включено и выключено затемнением кнопок. Если хотите, чтобы кнопка не нажималась, то вам нужно в обработчике команды это прописать.
