### ISSUE TITLE
Исключить из интеграции

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#175]
Нет возможности исключить из интеграции тип устройства

![snapshot](http://docs.ih-systems.com:40000/report/eE371qXCV.png)

- browser
  - name: Chrome
  - version: 96.0.4664.55
- os
  - name: macOS
  - version: 10.15.7
  - versionName: Catalina
- platform
  - type: desktop
  - vendor: Apple
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm
  - osUptime: 9d 23h 27m
  - uptime: 4d 17h 56m
  - port: 8089
  - server: intrahouse_v5
  - serverVersion: 5.5.121
  - project: demo_1609267773534
  - projectVersion: 5.5
- memory
  - os_total_free: 998 Mb / 457 Mb
  - process_rss: 89.3 Mb
  - process_heap_total: 24 Mb
  - process_heap_used: 19.6 Mb

**Comment by goodspeed1986** [comment]
В типе нет смысла исключать
