### ISSUE TITLE
Расписание для мультисценария

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#176]
Не работает расписание для мультисценариев

![snapshot](http://docs.ih-systems.com:40000/report/3i67kQF3q.png)

- browser
  - name: Electron
  - version: 12.2.1
- os
  - name: macOS
  - version: 12.0.1
- platform
  - type: desktop
  - vendor: Apple
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm
  - osUptime: 1d 20h 38m
  - uptime: 1d 20h 38m
  - port: 8088
  - server: intrahouse_v5
  - serverVersion: 5.5.121
  - project: intrahouse
  - projectVersion: 5.5
- memory
  - os_total_free: 923.2 Mb / 465.1 Mb
  - process_rss: 81.7 Mb
  - process_heap_total: 20.5 Mb
  - process_heap_used: 16.8 Mb

**Comment by nimargolis** [comment]
Да, мультисценарии в список не выбираются - нужен вероятно двухэтажный droplist:  сценарий - экземпляры

**Comment by nimargolis** [comment]
Работает v5.12.6
