### ISSUE TITLE
Циклический сценарий

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#177]
При выборе циклического сценария, не дает сохранить, пока не выберешь день недели или ежедневный запуск на другом типе запуска сценария, например в заданное время.

![snapshot](http://docs.ih-systems.com:40000/report/TZ5_YyQYW.png)

- browser
  - name: Electron
  - version: 12.2.1
- os
  - name: macOS
  - version: 12.0.1
- platform
  - type: desktop
  - vendor: Apple
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm
  - osUptime: 1d 20h 45m
  - uptime: 1d 20h 45m
  - port: 8088
  - server: intrahouse_v5
  - serverVersion: 5.5.121
  - project: intrahouse
  - projectVersion: 5.5
- memory
  - os_total_free: 923.2 Mb / 464.3 Mb
  - process_rss: 81.8 Mb
  - process_heap_total: 20.5 Mb
  - process_heap_used: 13.1 Mb

**Comment by nimargolis** [comment]
Исправлено в 5.5.135
