### ISSUE TITLE
После обновления перестал работать modbus

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#179]
Доброе время суток. Обновился на последнюю версию.

![snapshot](http://docs.ih-systems.com:40000/report/_KQw47Ox2.png)

- browser
  - name: Chrome
  - version: 96.0.4664.45
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm64
  - osUptime: 0d 0h 16m
  - uptime: 0d 0h 16m
  - port: 8088
  - server: intrahouse_v5
  - serverVersion: 5.5.138
  - project: intrahouse_metro
  - projectVersion: 5.5
- memory
  - os_total_free: 963.7 Mb / 215 Mb
  - process_rss: 78.7 Mb
  - process_heap_total: 25.7 Mb
  - process_heap_used: 16.8 Mb

**Comment by goodspeed1986** [comment]
Выпустили обновление
