### ISSUE TITLE
Проблемы с getSysTime

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#189]
Изменил настройки локации на свои. После этого перестала работать функция getSysTime. После отката настроек тоже не работает

![snapshot](http://docs.ih-systems.com:40000/report/nSsxiH4xU.png)

- browser
  - name: Opera
  - version: 82.0.4227.33
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm
  - osUptime: 20d 20h 1m
  - uptime: 0d 0h 1m
  - port: 8089
  - server: intrahouse_v5
  - serverVersion: 5.7.1
  - project: project_berezovaya15
  - projectVersion: 5.7
- memory
  - os_total_free: 3.7 Gb / 2.5 Gb
  - process_rss: 70.5 Mb
  - process_heap_total: 12.9 Mb
  - process_heap_used: 11.9 Mb

**Comment by nimargolis** [comment]
Ошибка воспроизводится только если число (широта или долгота) введены не в том формате. Возможно, используется запятая вместо точки. Или знак градус/минута? Ожидается вещественное число с точкой
TODO
- Проверять формат при сохранении 
- Использовать новое значение сразу (сейчас работает только после перезагрузки сервера)

**Comment by nimargolis** [comment]
ccc

**Comment by nimargolis** [comment]
cccc
