### ISSUE TITLE
не открывается экран

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#190]
сделал импорт проекта из V4

![snapshot](http://docs.ih-systems.com:40000/report/s19WSr0Lk.png)

- browser
  - name: Microsoft Edge
  - version: 96.0.1054.62
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm
  - osUptime: 21d 5h 22m
  - uptime: 0d 0h 17m
  - port: 8089
  - server: intrahouse_v5
  - serverVersion: 5.7.1
  - project: usadba31052021_fromV4
  - projectVersion: 5.7
- memory
  - os_total_free: 927.1 Mb / 49.9 Mb
  - process_rss: 66.9 Mb
  - process_heap_total: 16.7 Mb
  - process_heap_used: 15 Mb

**Comment by goodspeed1986** [comment]
Создайте новый экран. Скорее всего проблема при переходе с 4 версии. Визуализацию придется сделать с нуля.
