### ISSUE TITLE
киоск

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#194]
В настройках Доступ/Учетные записи для мобильного интерфейса необходимо выбрать стартовый экран при загрузке приложения: 
Где это в V5 версии?

![snapshot](http://docs.ih-systems.com:40000/report/4yqy1FKdl.png)

- browser
  - name: Chrome
  - version: 96.0.4664.110
- os
  - name: Windows
  - version: NT 6.1
  - versionName: 7
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm64
  - osUptime: 3d 17h 48m
  - uptime: 1d 5h 53m
  - port: 8088
  - server: intrahouse_v5
  - serverVersion: 5.7.1
  - project: demo_1640456924263
  - projectVersion: 5.7
- memory
  - os_total_free: 963.7 Mb / 190.1 Mb
  - process_rss: 97.3 Mb
  - process_heap_total: 29.5 Mb
  - process_heap_used: 25.4 Mb

**Comment by goodspeed1986** [comment]
В 5 версии можно выбрать только стартовый экран. Для мобильной версии настройки нет. Можете создать пользователя mobile и установить ему стартовый экран для мобильной верстки
