### ISSUE TITLE
не запускается плагин CCTV

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#208]
после запуска плагина сразу останавливается с ошибкой

![snapshot](http://docs.ih-systems.com:40000/report/M1i3b8zPy.png)

- browser
  - name: Microsoft Edge
  - version: 96.0.1054.62
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm
  - osUptime: 0d 2h 24m
  - uptime: 0d 0h 2m
  - port: 8089
  - server: intrahouse_v5
  - serverVersion: 5.7.1
  - project: usadba31052021_fromV4
  - projectVersion: 5.7
- memory
  - os_total_free: 927.1 Mb / 198.5 Mb
  - process_rss: 58.9 Mb
  - process_heap_total: 14.5 Mb
  - process_heap_used: 12.2 Mb

**Comment by goodspeed1986** [comment]
Установите уровень логирования на высокий и пришлите пожалуйста лог при запуске плагина
