### ISSUE TITLE
Нет соединения с брокером

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#213]
Нет соединения с брокером

![snapshot](http://docs.ih-systems.com:40000/report/G3q6rXLvG.png)

- browser
  - name: Opera
  - version: 82.0.4227.58
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm
  - osUptime: 0d 0h 16m
  - uptime: 0d 0h 16m
  - port: 8088
  - server: intrahouse_v5
  - serverVersion: 5.8.6
  - project: intrahouse
  - projectVersion: 5.8
- memory
  - os_total_free: 923.2 Mb / 538.3 Mb
  - process_rss: 64.3 Mb
  - process_heap_total: 18.5 Mb
  - process_heap_used: 11 Mb

**Comment by goodspeed1986** [comment]
Проверьте соединение с брокером
