### ISSUE TITLE
не могу подключится к овен opcua серверу

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#217]
В появившемся окне указать URL и порт OwenСloud, используемый протоколом OPC UA:
opc.tcp://opc.owencloud.ru:4843. для теста можно использовать данные от демо-аккаунта:
имя пользователя demo@owen.ru, пароль demo123). После этого нужно нажать кнопку
Готово

![snapshot](http://docs.ih-systems.com:40000/report/fhC5nNTEA.png)

- browser
  - name: Chrome
  - version: 98.0.4758.82
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: amd64
  - osUptime: 12d 0h 19m
  - uptime: 10d 14h 1m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.8.6
  - project: demo_1643963197685
  - projectVersion: 5.8
- memory
  - os_total_free: 3 Gb / 192.4 Mb
  - process_rss: 87.8 Mb
  - process_heap_total: 32.4 Mb
  - process_heap_used: 24.6 Mb

**Comment by goodspeed1986** [comment]
К вашему сервису нет доступа через OPC UA. Я пробовал через разные клиенты.
