### ISSUE TITLE
изменение уставки овен ТРМ210

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#218]
SP регистр 2
нет функции записи 16 (0x10) !

![snapshot](http://docs.ih-systems.com:40000/report/XT1a7oihp.png)

- browser
  - name: Chrome
  - version: 98.0.4758.82
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: amd64
  - osUptime: 12d 0h 27m
  - uptime: 10d 14h 9m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.8.6
  - project: demo_1643963197685
  - projectVersion: 5.8
- memory
  - os_total_free: 3 Gb / 189.5 Mb
  - process_rss: 87.7 Mb
  - process_heap_total: 32.4 Mb
  - process_heap_used: 26.7 Mb

**Comment by goodspeed1986** [comment]
16 функция Modbus автоматически используется плагином в том случае, если вам надо одновременно записать больше чем 1 регистр.
