### ISSUE TITLE
Проблема с записью значения

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#224]
Добрый день. Столкнулся с такой проблемой: был создан пользовательский обработчик с простейшим функционалом - из свойства "total_consumption" вычитать "consumption_before" и полученное значение записывать в "consumption_last_hour", которые вы можете видеть на скриншоте. Всё работает корректно, до момента с привязкой канала для записи. В этом случае всегда отображается значение "0", хотя в отладчике можно видеть правильно посчитанные обработчиком значения. 
Другими словами, внутренняя переменная считается корректно, однако момент с её записью уже не работает. 

![snapshot](http://docs.ih-systems.com:40000/report/2CrkmkwL4.png)

- browser
  - name: Chrome
  - version: 98.0.4758.102
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm
  - osUptime: 25d 3h 7m
  - uptime: 4d 3h 51m
  - port: 8088
  - server: intrahouse_v5
  - serverVersion: 5.8.23
  - project: burgerdisp
  - projectVersion: 5.8
- memory
  - os_total_free: 494.9 Mb / 14.2 Mb
  - process_rss: 54.4 Mb
  - process_heap_total: 22.2 Mb
  - process_heap_used: 14.2 Mb

**Comment by goodspeed1986** [comment]
Канал работает в две стороны. Когда вы в него, что то пишете, дальше он ждет обратную связь от плагина, что данные записались. Вам необходимо проверить правильность настройки канало на плагине.
