### ISSUE TITLE
Ошибка zigbee

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#226]
При сканировании каналов всплывает сообщение "Cannot read properties of undefined (reading 'error')"

![snapshot](http://docs.ih-systems.com:40000/report/g7skcFDnc.png)

- browser
  - name: Yandex Browser
  - version: 22.3.0.2430
- os
  - name: Windows
  - version: NT 6.1
  - versionName: 7
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm64
  - osUptime: 0d 2h 20m
  - uptime: 0d 0h 5m
  - port: 8088
  - server: intrahouse_v5
  - serverVersion: 5.8.32
  - project: demo_1648676386337
  - projectVersion: 5.8
- memory
  - os_total_free: 963.7 Mb / 128.5 Mb
  - process_rss: 69.8 Mb
  - process_heap_total: 20.7 Mb
  - process_heap_used: 19.9 Mb

**Comment by goodspeed1986** [comment]
Попробуйте удалить плагин вручную из папки /var/lib/ih-v5/plugins и снова установить через систему. Мы используем версию zigbee2mqtt, возможно, что то пошло не так.
