### ISSUE TITLE
Проблема с zigbee

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#227]
Постоянно отваливается то один то второй выключатель

![snapshot](http://docs.ih-systems.com:40000/report/WnJx66AIe.png)

- browser
  - name: Opera
  - version: 84.0.4316.42
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm64
  - osUptime: 46d 12h 42m
  - uptime: 4d 3h 18m
  - port: 8088
  - server: intrahouse_v5
  - serverVersion: 5.8.32
  - project: intrahouse
  - projectVersion: 5.8
- memory
  - os_total_free: 961.8 Mb / 78.1 Mb
  - process_rss: 96.9 Mb
  - process_heap_total: 29.1 Mb
  - process_heap_used: 26.2 Mb

**Comment by goodspeed1986** [comment]
Данный плагин сделан на базе ZigBee2mqtt. Все проблемы связанные с устройствами zigbee вам необходимо задавать на страничке данного проекта. Все настройки для данного проекта находятся в папке data.
