### ISSUE TITLE
Установка плагина

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#230]
Не удается установить плагин MB TCP/IP и OPC UA

![snapshot](http://docs.ih-systems.com:40000/report/lHG2E8T1x.png)

- browser
  - name: Chrome
  - version: 101.0.4951.64
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: windows
  - arch: amd64
  - osUptime: 0d 0h 11m
  - uptime: 0d 0h 4m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.8.32
  - project: demo_1652863925197
  - projectVersion: 5.5
- memory
  - os_total_free: 3.9 Gb / 1.4 Gb
  - process_rss: 59 Mb
  - process_heap_total: 21.1 Mb
  - process_heap_used: 20.3 Mb

**Comment by goodspeed1986** [comment]
Протестировал на своей Windows 10 машине, все установилось корректно. Видимо при установке пошло, что то не так. Сама установка представляет из себя просто копирование zip архива с github и распаковка его. Поэтому предлагаю вам попробовать удалить эти плагины вручную из папки C:\ProgramData\ih-v5\plugins если они там есть и попробовать установить через импорт (стрелочка справа сверху в админке), скачанные с github релизы плагинов. 
https://github.com/intrahouseio/ih-v5-modbus-plugin/archive/refs/tags/v5.5.14.zip
https://github.com/intrahouseio/ih-v5-opcua-plugin/archive/refs/tags/v5.5.5.zip
Если не получится, то предлагаю связаться с нами через телеграмм.
Есть еще один вариант, установить систему на Linux, например ubuntu на виртуалке или на свободной железке
