### ISSUE TITLE
заблокировался сценарий

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#241]
Не понимаю, что произошло. Сценарий работал, потом заблокировался и не дает разблокироваться. 
В чем ошибка? 

![snapshot](http://docs.ih-systems.com:40000/report/cv9rwMJkq.png)

- browser
  - name: Microsoft Edge
  - version: 101.0.1210.53
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm64
  - osUptime: 15d 20h 3m
  - uptime: 1d 13h 16m
  - port: 8088
  - server: intrahouse_v5
  - serverVersion: 5.8.32
  - project: demo_1645207861476
  - projectVersion: 5.8
- memory
  - os_total_free: 963.7 Mb / 36.9 Mb
  - process_rss: 103.7 Mb
  - process_heap_total: 33 Mb
  - process_heap_used: 26.2 Mb

**Comment by nimargolis** [comment]
В строке _this.info(...., 'состояние переключено через телеграмм')_   нет завершающей кавычки
