### ISSUE TITLE
getSysTime - проверить, добавить опцию next

### ISSUE THREAD

**Issue by goodspeed1986** [intrahouseio/ih-v5#257]
Если вызывать this.getSysTime('sunset') без параметров, то вовзращает время заката или рассвета по UTC

**Comment by nimargolis** [comment]
this.getSysTime('sunrise', 'next') - вернет ближайший рассвет / закат

**Comment by nimargolis** [comment]
> Если вызывать this.getSysTime('sunset') без параметров, то вовзращает время заката или рассвета по UTC
На сервере время было не локальное, а UTC
