### ISSUE TITLE
Экспорт папки с изображениями

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#27]
При правом клике по папке с изображениями и попытке экспорта получаем error: Response return status: 404

![snapshot](http://docs.ih-systems.com:40000/report/Wa50aJpr6.png)

- browser
  - name: Chrome
  - version: 86.0.4240.111
- os
  - name: macOS
  - version: 10.13.6
  - versionName: High Sierra
- platform
  - type: desktop
  - vendor: Apple
- engine
  - name: Blink
- server
  - platform: linux
  - arch: amd64
  - osUptime: 10d 23h 28m
  - uptime: 0d 3h 20m
  - port: 49903
  - project: smarthome2
- memory
  - os_total_free: 7.6 Gb / 4 Gb
  - process_rss: 59.1 Mb
  - process_heap_total: 20.3 Mb
  - process_heap_used: 18.7 Mb

**Comment by nimargolis** [comment]
Изображения из папки выгружаются в zip без учета папок. 
Также можно загружать изображения из zip-файла
