### ISSUE TITLE
цифры температуры съезжают на несколько пикселов вверх

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#28]
Не знаю как прикрепить изображение в баг-репорт, поэтому пишу сюда. 
В пользовательском интерфейсе в демонстрационном проекте с планами дома на первом этаже есть датчики температуры с возможностью просмотра истории (в гараже). При работе в Chrome при открытии и закрытии диалогового окна истории цифры температуры съезжают на несколько пикселов вверх. На картинке - 20 и 18,3. В Safari такого не наблюдается.

![image](https://user-images.githubusercontent.com/25459940/97953362-49d45080-1db1-11eb-86b9-adc8aceeeaa3.png)

**Comment by fast0490f** [comment]
Экшен-зона шаблона  была длиньше (height) чем сам шаблон, при нажатии происходит фокус на зону и соотвествено прокручивание
