### ISSUE TITLE
modbuse

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#292]
нет настройки подключения

![snapshot](http://docs.ih-systems.com:40000/report/OdUTqVv1k.png)

- browser
  - name: Microsoft Edge
  - version: 103.0.1264.37
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: windows
  - arch: amd64
  - osUptime: 9d 13h 10m
  - uptime: 0d 0h 3m
  - port: 8088
  - server: intrahouse_v5
  - serverVersion: 5.9.22
  - project: demo_1656736637374
  - projectVersion: 5.9
- memory
  - os_total_free: 7.8 Gb / 3.4 Gb
  - process_rss: 58.2 Mb
  - process_heap_total: 20.3 Mb
  - process_heap_used: 19.1 Mb

**Comment by goodspeed1986** [comment]
ПРоблема скорее всего связана с тем, что плагин установился некорректно из-за настройки в Windows количества символов в командной строке. Необходимо увеличить количество символов в командной строке Windows
