### ISSUE TITLE
Запись в главный журнал из устройства

### ISSUE THREAD

**Issue by goodspeed1986** [intrahouseio/ih-v5#295]
При выборе галочки записи в главный журнал для свойства устройства в журнале появляется запись без Сообщения если не задействован обработчик Значение в виде строки. Необходимо добавить Сообщение, состоящее из Названия свойства + Значение

**Comment by goodspeed1986** [comment]
Для записи Сообщений в главный журнал устройства обязательно должно быть установлено представление в виде Строки

**Comment by nimargolis** [comment]
v5.9.25
