### ISSUE TITLE
Не отображаются кнопки 

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#30]
хром

![snapshot](http://docs.ih-systems.com:40000/report/XtVyy6Fj9.png)

- browser
  - name: Chrome
  - version: 86.0.4240.111
- os
  - name: macOS
  - version: 10.15.7
  - versionName: Catalina
- platform
  - type: desktop
  - vendor: Apple
- engine
  - name: Blink
- server
  - platform: linux
  - arch: amd64
  - osUptime: 11d 15h 7m
  - uptime: 0d 12h 44m
  - port: 49903
  - project: smarthome2
- memory
  - os_total_free: 7.6 Gb / 4 Gb
  - process_rss: 62.1 Mb
  - process_heap_total: 24.3 Mb
  - process_heap_used: 20.4 Mb

**Comment by fast0490f** [comment]
не удалось поймать для выяснения ситации
