### ISSUE TITLE
Орфографическая ошибка

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#312]
Опечатка

![snapshot](http://docs.ih-systems.com:40000/report/MC27wYlMv.png)

- browser
  - name: Chrome
  - version: 103.0.0.0
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: amd64
  - osUptime: 281d 16h 59m
  - uptime: 112d 22h 8m
  - port: 5001
  - server: intrascada_v5
  - serverVersion: 5.8.37-beta
  - project: demo_intrascada_1639738326147
  - projectVersion: 5.8
- memory
  - os_total_free: 3.8 Gb / 288.5 Mb
  - process_rss: 103.3 Mb
  - process_heap_total: 37.6 Mb
  - process_heap_used: 32.9 Mb

**Comment by nimargolis** [comment]
Было в 5.8. В 5.9 уже исправлено
