### ISSUE TITLE
Добавить тип BigInt для свойства в тип устройства

### ISSUE THREAD

**Issue by goodspeed1986** [intrahouseio/ih-v5#327]
Добавить тип BigInt для свойства в тип устройства. Необходимо для использования вместе с плагином Modbus

**Comment by nimargolis** [comment]
Нужно на уровне канала тогда явно задавать тип, и учитывать при получении данных с канала. И контролировать выполнение операций со значениями (может возникнуть исключение). Предлагаю в плагинах преобразовывать в Number ( в js 2^53-1). Вернуться позже, если будет потребность работы со значениями больше.
