### ISSUE TITLE
Не импортируются изображения

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#329]
Не импортируются изображения всех перечисленных в документации форматов, а также zip файлы. К сожалению, заскринить ошибку невозможно, так как при появлении всплывающего окна зона строки состояния, где находится кнопка "Сообщить о проблеме", недоступна. Не загружаются как новые, так и экспортированные из проекта изображения.

![snapshot](http://docs.ih-systems.com:40000/report/ofv_oIG0E.png)

- browser
  - name: Firefox
  - version: 89.0
- os
  - name: Linux
- platform
  - type: desktop
- engine
  - name: Gecko
  - version: 20100101
- server
  - platform: linux
  - arch: amd64
  - osUptime: 0d 21h 42m
  - uptime: 0d 15h 31m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.9.30
  - project: MyFirstProject
  - projectVersion: 5.9
- memory
  - os_total_free: 5.7 Gb / 132.3 Mb
  - process_rss: 77.5 Mb
  - process_heap_total: 24.6 Mb
  - process_heap_used: 19.9 Mb

**Comment by nimargolis** [comment]
Было изменение param - исправлено начиная с 5.9.33
