### ISSUE TITLE
Не передаются ошибки в канале - плагин HTTP

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#333]
Ошибки  канала плагина HTTP не передаются устанавливают ошибку запроса , в котором находится канал и не привязываются к свойству error связанного с каналом устройства.
Соответственно, устройство в системе не понимает работает ли связанный с ним исполнитель или нет.

![snapshot](http://docs.ih-systems.com:40000/report/a9kzayUoq.png)

- browser
  - name: Firefox
  - version: 103.0
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Gecko
  - version: 20100101
- server
  - platform: linux
  - arch: arm
  - osUptime: 4d 9h 10m
  - uptime: 0d 10h 42m
  - port: 8088
  - server: intrahouse_v5
  - serverVersion: 5.9.30
  - project: project_KECH
  - projectVersion: 5.9
- memory
  - os_total_free: 1.8 Gb / 1 Gb
  - process_rss: 88.8 Mb
  - process_heap_total: 25.4 Mb
  - process_heap_used: 19.7 Mb

**Comment by nimargolis** [comment]
Доработать плагин http 
1. Включить chstatus
2. Возможность установить значение состояния после выполнения команды - как было в 4
