### ISSUE TITLE
Загрузка изображений

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#353]
При попытки загрузить изображение
из файла, выдает ошибку.
Причем пробывал выгрузить - все идет процесс, это же изображение пытаюсь загрузить- ошибка.

![snapshot](http://docs.ih-systems.com:40000/report/3i_7LI9qR.png)

- browser
  - name: Microsoft Edge
  - version: 105.0.1343.42
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: windows
  - arch: amd64
  - osUptime: 8d 8h 31m
  - uptime: 0d 7h 57m
  - port: 8088
  - server: intrahouse_v5
  - serverVersion: 5.9.30
  - project: gidrousel
  - projectVersion: 5.9
- memory
  - os_total_free: 7.8 Gb / 3 Gb
  - process_rss: 57.7 Mb
  - process_heap_total: 21.6 Mb
  - process_heap_used: 19.3 Mb

**Comment by nimargolis** [comment]
Исправлено в версии 5.9.37-beta
