### ISSUE TITLE
Название экземляров плагина

### ISSUE THREAD

**Issue by goodspeed1986** [intrahouseio/ih-v5#392]
Дать возможность переименовывать названия экземпляров плагина

**Comment by nimargolis** [comment]
Добавлена возможность ввести name для экземпляра плагина, при этом ID не меняется.  
Если name заполнено - в дереве будет отображаться название, если пустое - будет ID как раньше. 
name - это не идентификатор, а произвольный текст  
Чтобы заработало, нужно на форме formPluginCommon каждого плагина   добавить поле name.
