### ISSUE TITLE
Границы параметров плагина

### ISSUE THREAD

**Issue by goodspeed1986** [intrahouseio/ih-v5#393]
Добавить проверку на границы вводимых значений в параметрах плагина

**Comment by nimargolis** [comment]
Реализованы правила валидации полей на формах, использующих таблицу units (formPluginCommon по умолчанию)
[Правила валидации](https://docs.intrascada.com/ru/pg144) прописываются в манифесте плагина.   
На текущий момент включают:
"min",  "max", "IP", "IPv4","IPv6", "notempty", "validid"

Для реализации возможности нужно прописать правила в манифестах плагинов
