### ISSUE TITLE
Поломались отчеты

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#408]
Если к виджету привязан отчет то экран контейнера не открывается

![snapshot](http://docs.ih-systems.com:40000/report/F5_e8WK0f.png)

- browser
  - name: Electron
  - version: 12.2.1
- os
  - name: Windows
  - version: NT 6.1
  - versionName: 7
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: amd64
  - osUptime: 14d 14h 36m
  - uptime: 0d 0h 7m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.11.54
  - project: intrascada_IP_REIHARDT
  - projectVersion: 5.11
- memory
  - os_total_free: 1.8 Gb / 387.8 Mb
  - process_rss: 88.4 Mb
  - process_heap_total: 26.4 Mb
  - process_heap_used: 20 Mb

**Comment by nimargolis** [comment]
Не подтверждено
