### ISSUE TITLE
установка плашина CCTV

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#419]
добрый день.

Пытаюсь установить плагин CCTV. сервер у становлен на борт wirenboard 7.
при попытке выдвет ошибку.

Тоже самое с обновлением самого ПО.
В чем может быть причина?

за ранее спасибо!

![snapshot](http://docs.ih-systems.com:40000/report/vmj_ABFxh.png)

- browser
  - name: Yandex Browser
  - version: 22.11.5.709
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm
  - osUptime: 3d 0h 35m
  - uptime: 0d 18h 2m
  - port: 8088
  - server: intrahouse_v5
  - serverVersion: 5.11.40
  - project: demo_project
  - projectVersion: 5.11
- memory
  - os_total_free: 1.9 Gb / 1.5 Gb
  - process_rss: 95.2 Mb
  - process_heap_total: 27.5 Mb
  - process_heap_used: 18.8 Mb

**Comment by nimargolis** [comment]
Проблема загрузки - сетевые настройки или нет выхода в интернет
