### ISSUE TITLE
Нет доступа к интерфейсу пользователя.

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#425]
Невозможно войти в пользовательский интерфейс. После нескольких попыток почему-то снова попадаю в админку.

![snapshot](http://docs.ih-systems.com:40000/report/3WpRCGg7i.png)

- browser
  - name: Chrome
  - version: 109.0.0.0
- os
  - name: Windows
  - version: NT 6.1
  - versionName: 7
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: amd64
  - osUptime: 0d 18h 58m
  - uptime: 0d 18h 58m
  - port: 8088
  - server: intrahouse_v5
  - serverVersion: 5.12.2
  - project: o_project_1674452392876
  - projectVersion: 5.12
- memory
  - os_total_free: 1.8 Gb / 1.1 Gb
  - process_rss: 150.1 Mb
  - process_heap_total: 37.2 Mb
  - process_heap_used: 28.1 Mb

**Comment by nimargolis** [comment]
Возможно, нужно выводить сообщение ( или спец страницу), если дефолтный экран пользователя не задан
