### ISSUE TITLE
Не вижу данных о температуре с датчика

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#426]
Сутки назад указал в свойствах датчика температуры сохраниять в БД 30 дней показания, снимаемые раз в 60 секунд.
Сегодня начал работать с системой и не могу увидеть данные за прошедшую ночь. Что я делаю неправильно?

![snapshot](http://docs.ih-systems.com:40000/report/OtcncrpMk.png)

- browser
  - name: Chrome
  - version: 109.0.0.0
- os
  - name: Windows
  - version: NT 6.1
  - versionName: 7
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: amd64
  - osUptime: 0d 21h 50m
  - uptime: 0d 21h 49m
  - port: 8088
  - server: intrahouse_v5
  - serverVersion: 5.12.2
  - project: o_project_1674452392876
  - projectVersion: 5.12
- memory
  - os_total_free: 1.8 Gb / 1.1 Gb
  - process_rss: 151.5 Mb
  - process_heap_total: 37.9 Mb
  - process_heap_used: 29.8 Mb

**Comment by nimargolis** [comment]
На этой форме показываются данные только за последний час. В 5.12.5 над таблицей добавлена надпись:
Выводятся данные за последний час.
