### ISSUE TITLE
Плагин модбас останавливается с ошибкой

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#427]
Плагин модбас останавливается с ошибкой. Началось после обновления плагина.

![snapshot](http://docs.ih-systems.com:40000/report/nqotIDX6d.png)

- browser
  - name: Yandex Browser
  - version: 23.1.1.1138
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: windows
  - arch: amd64
  - osUptime: 0d 2h 10m
  - uptime: 0d 2h 10m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.11.60
  - project: project_1675673191571
  - projectVersion: 5.11
- memory
  - os_total_free: 15.8 Gb / 11.2 Gb
  - process_rss: 80.3 Mb
  - process_heap_total: 29.1 Mb
  - process_heap_used: 27.6 Mb

**Comment by nimargolis** [comment]
Не подтверждено
