### ISSUE TITLE
Плагин Megad

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#52]
В расширении плагина прописано
Входящее от контроллера MegaD /md?pt=0
Передать в ответ 7:2

В логе сообщение от меги приходят, но в ответ ничего не передается. 

![snapshot](http://docs.ih-systems.com:40000/report/zJEANEoOw.png)

- browser
  - name: Chrome
  - version: 87.0.4280.88
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm
  - osUptime: 43d 19h 44m
  - uptime: 0d 1h 55m
  - port: 8088
  - project: nag
- memory
  - os_total_free: 974.3 Mb / 54.7 Mb
  - process_rss: 44.2 Mb
  - process_heap_total: 9.9 Mb
  - process_heap_used: 9 Mb

**Comment by nimargolis** [comment]
Исправлено:
- версия системы v5.1.10
- версия плагина MegaD v5.0.1
