### ISSUE TITLE
formPluginExtraTypeError

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#71]
при переключении на вкладку "Расширение" получаем ошибку

![snapshot](http://docs.ih-systems.com:40000/report/YRFfJa2P6.png)

- browser
  - name: Safari
  - version: 14.0.3
- os
  - name: macOS
  - version: 10.15.7
  - versionName: Catalina
- platform
  - type: desktop
  - vendor: Apple
- engine
  - name: WebKit
  - version: 605.1.15
- server
  - platform: linux
  - arch: arm
  - osUptime: 20d 5h 0m
  - uptime: 0d 0h 6m
  - port: 8088
  - project: sh_zp2
- memory
  - os_total_free: 973.7 Mb / 103.3 Mb
  - process_rss: 56.9 Mb
  - process_heap_total: 12.7 Mb
  - process_heap_used: 11.9 Mb

**Comment by nimargolis** [comment]
Исправлено в версии плагина MQTT 5.5.5. В манифест плагина добавлен флаг наличия вкладки Расширение:
"extratab":1,
