### ISSUE TITLE
Исчезли разделы!

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#74]
Куда пропала аналитика и базы данных ? пробовал удалять v5 и по новому ставить, мой проект загружает, на два раздела отсутствуют

![snapshot](http://docs.ih-systems.com:40000/report/r1vWbBj3W.png)

- browser
  - name: Opera
  - version: 76.0.4017.123
- os
  - name: Linux
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: amd64
  - osUptime: 0d 0h 24m
  - uptime: 0d 0h 3m
  - port: 8089
  - project: moi_dom
- memory
  - os_total_free: 3.7 Gb / 115.2 Mb
  - process_rss: 67.9 Mb
  - process_heap_total: 19.1 Mb
  - process_heap_used: 18 Mb

**Comment by goodspeed1986** [comment]
Для IntraHouse данные разделы недоступны, необходимо установить IntraScada.
