### ISSUE TITLE
Chart Multiline 

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#75]
Не понял как настроить Chart Multiline.
Сколько можно сделать одновременно перьев? 

![snapshot](http://docs.ih-systems.com:40000/report/Q1ur34tTQ.png)

- browser
  - name: Chrome
  - version: 91.0.4472.77
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: windows
  - arch: amd64
  - osUptime: 11d 17h 10m
  - uptime: 3d 18h 4m
  - port: 8088
  - project: project_1621839706820
- memory
  - os_total_free: 7.9 Gb / 3.7 Gb
  - process_rss: 40.7 Mb
  - process_heap_total: 22.6 Mb
  - process_heap_used: 20.6 Mb

**Comment by goodspeed1986** [comment]
Для того, чтобы добавить несколько перьев вам необходимо зайти в аналитику и создать график с несколькими перьями. А на контейнере в привязках уже выбрать данный график.
