### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#76]
Не удается загрузить проект Cherry

![snapshot](http://docs.ih-systems.com:40000/report/FPBiPtK_K.png)

- browser
  - name: Opera
  - version: 76.0.4017.177
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: windows
  - arch: amd64
  - osUptime: 0d 1h 26m
  - uptime: 0d 0h 2m
  - port: 8089
  - project: demo_1622920210575
- memory
  - os_total_free: 15.9 Gb / 10.7 Gb
  - process_rss: 55.5 Mb
  - process_heap_total: 19.1 Mb
  - process_heap_used: 15.8 Mb

**Comment by goodspeed1986** [comment]
Обновитесь до последней версии системы через интерфейс или через командную строку

**Comment by nimargolis** [comment]
Проблема связана с загрузкой zip под Windows. Исправлено в 5.5.20
