### ISSUE TITLE
Проблема импорта плагинов.

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#77]
Здравствуйте!
Версия V5. Любой плагин из библиотеки продуктов для версии V5 сопровождается ошибкой при импорте (см. скриншот). 

![snapshot](http://docs.ih-systems.com:40000/report/KPJvaX7w7.png)

- browser
  - name: Chrome
  - version: 90.0.4430.212
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: windows
  - arch: amd64
  - osUptime: 5d 17h 39m
  - uptime: 5d 17h 39m
  - port: 8088
  - project: demo_1622318195827
- memory
  - os_total_free: 5.8 Gb / 2.1 Gb
  - process_rss: 43.6 Mb
  - process_heap_total: 22.1 Mb
  - process_heap_used: 17.4 Mb

**Comment by nimargolis** [comment]
Была проблема импорта плагинов на сервере под Windows. Решено
