### ISSUE TITLE
Нет возможности добавить шрифт

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#90]
В проекте требуется использовать шрифт: inter и  Jost

![snapshot](http://docs.ih-systems.com:40000/report/5BV8x0JqG.png)

- browser
  - name: Chrome
  - version: 91.0.4472.114
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm64
  - osUptime: 0d 1h 50m
  - uptime: 0d 1h 49m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.5.32
  - project: demo_1624006767433
  - projectVersion: 5.5
- memory
  - os_total_free: 963.1 Mb / 387.8 Mb
  - process_rss: 79.6 Mb
  - process_heap_total: 24.7 Mb
  - process_heap_used: 17 Mb

**Comment by nimargolis** [comment]
duplicate #343
