### ISSUE TITLE
выравнивание логотипа кнопки

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#91]
Было бы удобно, если бы у кнопки можно было менять расположение картинки 

![snapshot](http://docs.ih-systems.com:40000/report/E_6vypj6P.png)

- browser
  - name: Chrome
  - version: 91.0.4472.114
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm64
  - osUptime: 0d 3h 1m
  - uptime: 0d 3h 1m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.5.32
  - project: demo_1624006767433
  - projectVersion: 5.5
- memory
  - os_total_free: 963.1 Mb / 380.3 Mb
  - process_rss: 80.7 Mb
  - process_heap_total: 25 Mb
  - process_heap_used: 18.1 Mb

**Comment by fast0490f** [comment]
В свойствах элемента (значок карандаш) есть необходимые параметры

**Comment by goodspeed1986** [comment]
Необходимо выравнять логотип и Текст кнопки или дать возможность настраивать отступы снизу для обоих элементов

**Comment by nimargolis** [comment]
Отразить возможности форматирования в документации
