### ISSUE TITLE
P2P неверный статус

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#94]
У меня плагин p2p остановлен с ошибкой, а состояние все равно пишет подключено.

![snapshot](http://docs.ih-systems.com:40000/report/7rR9ed7LA.png)

- browser
  - name: Safari
  - version: 14.1.1
- os
  - name: macOS
  - version: 10.15.7
  - versionName: Catalina
- platform
  - type: desktop
  - vendor: Apple
- engine
  - name: WebKit
  - version: 605.1.15
- server
  - platform: darwin
  - arch: arm64
  - osUptime: 0d 14h 38m
  - uptime: 0d 0h 3m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.5.32
  - project: demo_1621852904418
  - projectVersion: 5.5
- memory
  - os_total_free: 8 Gb / 93.2 Mb
  - process_rss: 78.3 Mb
  - process_heap_total: 20.4 Mb
  - process_heap_used: 19.5 Mb

**Comment by nimargolis** [comment]
На форму добавлено состояние плагина p2p. Статус при остановленном плагине сбрасывается. Версия 5.5.77
