### ISSUE TITLE
Значок на панель об ограничении лицензии

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#95]
Добавить значок на панель об ограничении лицензии по тегам, иначе не понятно почему не работают каналы. Выделить красным или желтым сообщение об ограничении функционала.
На будущее. Во вкладке лицензии сделать ссылку на переход в продукты для покупки лицензии.

![snapshot](http://docs.ih-systems.com:40000/report/O6Bghflb0.png)

- browser
  - name: Electron
  - version: 13.1.2
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm64
  - osUptime: 0d 6h 5m
  - uptime: 0d 6h 4m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.5.32
  - project: new_290621503
  - projectVersion: 5.5
- memory
  - os_total_free: 1.9 Gb / 25.1 Mb
  - process_rss: 82.1 Mb
  - process_heap_total: 31.6 Mb
  - process_heap_used: 23.4 Mb

**Comment by nimargolis** [comment]
Добавить индикатор в верхнюю строку состояния

**Comment by nimargolis** [comment]
Индикатор добавлен в 5.8
