### ISSUE TITLE
Ошибка у плагина эмуляции

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#96]
Происходит при добавлении канала

![snapshot](http://docs.ih-systems.com:40000/report/gqbJ8PcAR.png)

- browser
  - name: Chrome
  - version: 91.0.4472.124
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm64
  - osUptime: 4d 4h 45m
  - uptime: 0d 0h 22m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.5.32
  - project: demo_1624006767433
  - projectVersion: 5.5
- memory
  - os_total_free: 963.1 Mb / 416.6 Mb
  - process_rss: 71.2 Mb
  - process_heap_total: 24.2 Mb
  - process_heap_used: 21.9 Mb

**Comment by nimargolis** [comment]
Ошибка формы плагина. Выпущена новая версия emuls v5.5.1
