### ISSUE TITLE
пропали тренды

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#97]
После перезапуска БД, пропали тренды за предыдущие дни

![snapshot](http://docs.ih-systems.com:40000/report/3wyGbjx-k.png)

- browser
  - name: Chrome
  - version: 91.0.4472.124
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm64
  - osUptime: 0d 11h 10m
  - uptime: 0d 11h 8m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.5.32
  - project: demo_1624006767433
  - projectVersion: 5.5
- memory
  - os_total_free: 963.1 Mb / 287.9 Mb
  - process_rss: 75.7 Mb
  - process_heap_total: 25.7 Mb
  - process_heap_used: 22.9 Mb

**Comment by goodspeed1986** [comment]
Это связано с местом хранения базы. По умолчанию база стала храниться не в проекте, а в папке /var/lib/ih-home-automation/db/hist.db
