### ISSUE TITLE
не корректное отображение 

### ISSUE THREAD

**Issue by intrahouseio** [intrahouseio/ih-v5#99]
Требуется отображение о состояние (работа, остановка, авария). Был создан тестовый образец Test1  шаблон с состоянием работа зеленый остановка синий авария красный, с возможностью перехода на экран устройства, в дальнейшем был создан контейнер на основе этого в ходе работы было выявлено что в режиме работа данный элемент окрасился в требуемый цвет но при переходе на другой экран этот элемент окрашивался в базовый цвет. 

![snapshot](http://docs.ih-systems.com:40000/report/Hwp2fnIbf.png)

- browser
  - name: Chrome
  - version: 91.0.4472.124
- os
  - name: Windows
  - version: NT 10.0
  - versionName: 10
- platform
  - type: desktop
- engine
  - name: Blink
- server
  - platform: linux
  - arch: arm64
  - osUptime: 0d 1h 4m
  - uptime: 0d 1h 3m
  - port: 8088
  - server: intrascada_v5
  - serverVersion: 5.5.33
  - project: new_290621503
  - projectVersion: 5.5
- memory
  - os_total_free: 1.9 Gb / 24.9 Mb
  - process_rss: 76.2 Mb
  - process_heap_total: 29.9 Mb
  - process_heap_used: 24.9 Mb

**Comment by goodspeed1986** [comment]
Вам нужно вместо кнопки создать свой шаблон визуализации, где вы сможете сконфигурировать изменение цвета по состояние и назначит кнопки на переход на экран.
